### ISSUE TITLE
websocket-driver 0.7.2 not found

### ISSUE THREAD

**Issue by soumendrak** [IBM-Cloud/nodejs-data-lake-dashboard#1]
While running `npm install` getting issue that the version `0.7.2.` not found.     

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz
npm ERR! 404
npm ERR! 404  'websocket-driver@0.7.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nodejs-data-lake-dashboard'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

This should be changed to `0.7.3`. Mine worked after explicitly downloading the `0.7.3` version.    
`nodejs-data-lake-dashboard/package-lock.json` need to be changed.

**Comment by l2fprod** [comment]
this commit https://github.com/IBM-Cloud/nodejs-data-lake-dashboard/commit/8211500495650c88fbf554d08b1da3cc28bc42ad fixes the issue
